### ISSUE TITLE
Crash si le NE n envoie pas son nom.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#471]
AbeilleParser 2018-11-26 15:04:06[DEBUG];Type; fct; processAnnonce end, NE: {"809f":{"IEEE":"00124b0019944f87","capa":"8e","time":1543241041,"state":"configuration","action":"location->configuration","EP":"0B","modelIdentifier":"GLEDOPTO"}}
AbeilleParser 2018-11-26 15:04:06[DEBUG];Type; fct; processAnnonce ; Demande Current State Equipement qui doit etre cree
PHP Fatal error:  Uncaught Error: Call to a member function getCmd() on boolean in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php:1956
Stack trace:
#0 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php(2067): getNE('809f')
#1 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php(2207): processAnnonce(Array, Object(Mosquitto\Client), '0')
#2 {main}
  thrown in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 1956

**Comment by KiwiHC16** [comment]
Ne devrait plus se produire avec les tests ajoutés ce jour.
